apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticsGreen
  labels:
    app: staticsGreen
spec:
  selector:
    matchLabels:
      app: staticsGreen
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 0
  template:
    metadata:
      labels:
        app: staticsGreen
    spec:
      containers:
        - name: staticsGreen
          image: docker.io/aivlev/statics:v1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /__heartbeat__
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /__heartbeat__
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 2m
              memory: 10Mi
            requests:
              cpu: 2m
              memory: 10Mi