apiVersion: v1
kind: Service
metadata:
  name: staticsGreen
  labels:
    app: staticsGreen
spec:
  selector:
    app: staticsGreen
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP