apiVersion: apps/v1
kind: Deployment
metadata:
  name: statics
  labels:
    app: statics
spec:
  selector:
    matchLabels:
      app: statics
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: statics
    spec:
      volumes:
        - name: src
          emptyDir: { }
      initContainers:
        - name: prepare-statics
          image: alpine/git
          command:
            - git
            - clone
            - https://github.com/mdn/beginner-html-site-scripted
            - /static
          volumeMounts:
            - name: src
              mountPath: /static
      containers:
        - name: statics
          image: docker.io/aivlev/statics:v1.0.0
          imagePullPolicy: Always
          volumeMounts:
            - name: src
              mountPath: /static
          env:
            - name: PORT
              value: "8080"
            - name: STATICS_PATH
              value: "/static"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /__heartbeat__
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /__heartbeat__
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 2m
              memory: 10Mi
            requests:
              cpu: 2m
              memory: 10Mi