apiVersion: v1
kind: Service
metadata:
  name: statics
  labels:
    app: statics
spec:
  selector:
    app: statics
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP